dbfilename redis_queue.rdb
dir /home/tranquocbn/Desktop/frappe-bench-16/config/pids
pidfile /home/tranquocbn/Desktop/frappe-bench-16/config/pids/redis_queue.pid
bind 127.0.0.1
port 11001

aclfile /home/tranquocbn/Desktop/frappe-bench-16/config/redis_queue.acl
